### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ppbl** [ppbl/scicode#1]
The following is a list of goals to achieve before open source

- [x] CRUD of posts
- [x] Comment
- [x] Topics
- [x] Hot list
- [x] Deploy to server
- [x] Github login in
- [ ]  ~~Investigation on replacing [yew](https://github.com/yewstack/yew) with [dioxus](https://github.com/DioxusLabs/dioxus) (optional)~~
- [x] Review code and restructure
- [x]  Open source
